// Code generated by metricsgen. DO NOT EDIT.

package engine

import (
	"github.com/go-kit/kit/metrics/discard"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
)

func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
	labels := []string{}
	for i := 0; i < len(labelsAndValues); i += 2 {
		labels = append(labels, labelsAndValues[i])
	}
	return &Metrics{
		StatusBroadcasts: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "status_broadcasts",
			Help:      "Number of status broadcasts sent.",
		}, labels).With(labelsAndValues...),
		StatusBroadcastFailures: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "status_broadcast_failures",
			Help:      "Number of status broadcasts dropped due to backpressure.",
		}, labels).With(labelsAndValues...),
		AttestBroadcasts: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "attest_broadcasts",
			Help:      "Number of attestor commit broadcasts sent.",
		}, labels).With(labelsAndValues...),
		AttestBroadcastFailures: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "attest_broadcast_failures",
			Help:      "Number of attestor commit broadcasts dropped due to backpressure.",
		}, labels).With(labelsAndValues...),
		ProposalBroadcasts: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "proposal_broadcasts",
			Help:      "Number of proposal broadcasts sent.",
		}, labels).With(labelsAndValues...),
		ProposalBroadcastFailures: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "proposal_broadcast_failures",
			Help:      "Number of proposal broadcasts dropped due to backpressure.",
		}, labels).With(labelsAndValues...),
		Syncing: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "syncing",
			Help:      "Whether or not the sequencing engine is running. 1 if yes, 0 if no.",
		}, labels).With(labelsAndValues...),
		NumTxs: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "num_txs",
			Help:      "Number of transactions in the latest block.",
		}, labels).With(labelsAndValues...),
		TotalTxs: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "total_txs",
			Help:      "Total number of transactions processed by the sequencing engine.",
		}, labels).With(labelsAndValues...),
		BlockSizeBytes: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_size_bytes",
			Help:      "Size of the latest block in bytes.",
		}, labels).With(labelsAndValues...),
		LatestBlockHeight: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "latest_block_height",
			Help:      "Height of the latest applied block.",
		}, labels).With(labelsAndValues...),
	}
}

func NopMetrics() *Metrics {
	return &Metrics{
		StatusBroadcasts:          discard.NewCounter(),
		StatusBroadcastFailures:   discard.NewCounter(),
		AttestBroadcasts:          discard.NewCounter(),
		AttestBroadcastFailures:   discard.NewCounter(),
		ProposalBroadcasts:        discard.NewCounter(),
		ProposalBroadcastFailures: discard.NewCounter(),
		Syncing:                   discard.NewGauge(),
		NumTxs:                    discard.NewGauge(),
		TotalTxs:                  discard.NewGauge(),
		BlockSizeBytes:            discard.NewGauge(),
		LatestBlockHeight:         discard.NewGauge(),
	}
}
