// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	log "github.com/cometbft/cometbft/libs/log"
	mock "github.com/stretchr/testify/mock"

	query "github.com/cometbft/cometbft/libs/pubsub/query"

	txindex "github.com/cometbft/cometbft/state/txindex"

	types "github.com/cometbft/cometbft/abci/types"
)

// TxIndexerV2 is an autogenerated mock type for the TxIndexerV2 type
type TxIndexerV2 struct {
	mock.Mock
}

// AddBatch provides a mock function with given fields: b
func (_m *TxIndexerV2) AddBatch(b *txindex.Batch) error {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*txindex.Batch) error); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinalizeReindex provides a mock function with given fields: startHeight, endHeight
func (_m *TxIndexerV2) FinalizeReindex(startHeight int64, endHeight int64) error {
	ret := _m.Called(startHeight, endHeight)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeReindex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(startHeight, endHeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: hash
func (_m *TxIndexerV2) Get(hash []byte) (*types.TxResult, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.TxResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*types.TxResult, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func([]byte) *types.TxResult); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.TxResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Height provides a mock function with no fields
func (_m *TxIndexerV2) Height() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Height")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prune provides a mock function with given fields: curHeight
func (_m *TxIndexerV2) Prune(curHeight int64) error {
	ret := _m.Called(curHeight)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(curHeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, q, maxCount
func (_m *TxIndexerV2) Search(ctx context.Context, q *query.Query, maxCount int64) (chan types.TxResult, chan error) {
	ret := _m.Called(ctx, q, maxCount)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 chan types.TxResult
	var r1 chan error
	if rf, ok := ret.Get(0).(func(context.Context, *query.Query, int64) (chan types.TxResult, chan error)); ok {
		return rf(ctx, q, maxCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.Query, int64) chan types.TxResult); ok {
		r0 = rf(ctx, q, maxCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan types.TxResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.Query, int64) chan error); ok {
		r1 = rf(ctx, q, maxCount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}

// SetLogger provides a mock function with given fields: l
func (_m *TxIndexerV2) SetLogger(l log.Logger) {
	_m.Called(l)
}

// StartReindex provides a mock function with no fields
func (_m *TxIndexerV2) StartReindex() {
	_m.Called()
}

// NewTxIndexerV2 creates a new instance of TxIndexerV2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxIndexerV2(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxIndexerV2 {
	mock := &TxIndexerV2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
