// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	log "github.com/cometbft/cometbft/libs/log"

	mock "github.com/stretchr/testify/mock"

	query "github.com/cometbft/cometbft/libs/pubsub/query"

	types "github.com/cometbft/cometbft/types"
)

// BlockIndexer is an autogenerated mock type for the BlockIndexer type
type BlockIndexer struct {
	mock.Mock
}

// FinalizeReindex provides a mock function with given fields: startHeight, endHeight
func (_m *BlockIndexer) FinalizeReindex(startHeight int64, endHeight int64) error {
	ret := _m.Called(startHeight, endHeight)

	if len(ret) == 0 {
		panic("no return value specified for FinalizeReindex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(startHeight, endHeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Has provides a mock function with given fields: height
func (_m *BlockIndexer) Has(height int64) (bool, error) {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (bool, error)); ok {
		return rf(height)
	}
	if rf, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Index provides a mock function with given fields: _a0
func (_m *BlockIndexer) Index(_a0 types.EventDataNewBlockEvents) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.EventDataNewBlockEvents) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Prune provides a mock function with given fields: curHeight
func (_m *BlockIndexer) Prune(curHeight int64) error {
	ret := _m.Called(curHeight)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(curHeight)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, q, maxCount
func (_m *BlockIndexer) Search(ctx context.Context, q *query.Query, maxCount int64) (chan int64, chan error) {
	ret := _m.Called(ctx, q, maxCount)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 chan int64
	var r1 chan error
	if rf, ok := ret.Get(0).(func(context.Context, *query.Query, int64) (chan int64, chan error)); ok {
		return rf(ctx, q, maxCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *query.Query, int64) chan int64); ok {
		r0 = rf(ctx, q, maxCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *query.Query, int64) chan error); ok {
		r1 = rf(ctx, q, maxCount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(chan error)
		}
	}

	return r0, r1
}

// SetLogger provides a mock function with given fields: l
func (_m *BlockIndexer) SetLogger(l log.Logger) {
	_m.Called(l)
}

// StartReindex provides a mock function with no fields
func (_m *BlockIndexer) StartReindex() {
	_m.Called()
}

// NewBlockIndexer creates a new instance of BlockIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockIndexer {
	mock := &BlockIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
