syntax = "proto3";

package tmibc.core.commitment.v1;

option go_package = "github.com/cometbft/cometbft/proto/tmibc/core/commitment/v1";

import "gogoproto/gogo.proto";
import "cosmos/ics23/v1/proofs.proto";

// MerkleProof is a wrapper type over a chain of CommitmentProofs.
// It demonstrates membership or non-membership for an element or set of
// elements, verifiable in conjunction with a known commitment root. Proofs
// should be succinct.
// MerkleProofs are ordered from leaf-to-root
message MerkleProof {
  repeated cosmos.ics23.v1.CommitmentProof proofs = 1;
}
